name: Build Tokens on Commit

on:
  push:
    branches:
      - main # Adjust this to the branch you want to trigger the action on

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # install dependencies
      - name: Install Dependencies
        run: npm install

      # build tokens
      - name: Build Tokens
        run: npm run build

      # commit changes
      - name: Commit Changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          commit: "Build Tokens"
