name: Build Tokens on Commit

on:
  push:
    branches:
      - main # Adjust this to the branch you want to trigger the action on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Adjust this to your Node.js version

      - name: Install dependencies
        run: npm ci

      - name: Run build script
        run: npm run build
